// Draws the contribution mountains. Runs in GitHub Actions every few hours, or locally with GITHUB_TOKEN set.
// The interactive pictures (live room, tic-tac-toe, sticker wall, the cat) are not drawn here: the adilkan.com server draws
// them on every page view with the same scenes.mjs and games.mjs, so a button press shows up at once.
// 1) fetches a year of public contributions, 2) draws the ridge for both themes, 3) force-pushes it as a single commit to lab-output.
import {mkdirSync, writeFileSync, rmSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {THEMES} from './palette.mjs';
import {mountains} from './scenes.mjs';

const REPO = process.env.REPO || 'adilkananarbekov/adilkananarbekov';
const LOGIN = REPO.split('/')[0];
const TOKEN = process.env.GITHUB_TOKEN;
if (!TOKEN) throw new Error('GITHUB_TOKEN is required');
const BRANCH = 'lab-output';
const auth = `AUTHORIZATION: basic ${Buffer.from(`x-access-token:${TOKEN}`).toString('base64')}`;
if (process.env.GITHUB_ACTIONS) console.log(`::add-mask::${auth.slice(21)}`);

// 1. Contributions over the last year. Without them nothing is published, so the previous picture stays.
const q = `query($login:String!){user(login:$login){contributionsCollection{contributionCalendar{totalContributions weeks{contributionDays{contributionCount date}}}}}}`;
const res = await fetch('https://api.github.com/graphql', {method: 'POST', headers: {authorization: `Bearer ${TOKEN}`, 'content-type': 'application/json', 'user-agent': 'adilkan-lab'}, body: JSON.stringify({query: q, variables: {login: LOGIN}})});
if (!res.ok) throw new Error(`contributions: ${res.status}`);
const cal = (await res.json()).data.user.contributionsCollection.contributionCalendar;
const weeks = cal.weeks.map(w => ({start: w.contributionDays[0].date, count: w.contributionDays.reduce((s, d) => s + d.contributionCount, 0)}));

// 2. Pictures.
const dir = join(tmpdir(), `lab-${process.pid}`);
rmSync(dir, {recursive: true, force: true}); mkdirSync(dir, {recursive: true});
for (const t of Object.values(THEMES)) writeFileSync(join(dir, `mountains-${t.name}.svg`), mountains(t, weeks, cal.totalContributions));
writeFileSync(join(dir, 'README.md'), '# lab-output\n\nGenerated by `lab/run.mjs` (workflow `lab`): the contribution mountains of the profile README. Rewritten on every run.\n');

// 3. Publish as a single commit on the output branch. The credential travels in git's environment config, never in argv, a URL or a log line.
const git = (args, extraEnv = {}) => {
  try { execFileSync('git', args, {cwd: dir, env: {...process.env, GIT_TERMINAL_PROMPT: '0', ...extraEnv}, stdio: ['ignore', 'ignore', 'pipe']}); }
  catch (e) { throw new Error(`git ${args.find(a => !a.startsWith('-') && !a.includes('='))} failed (exit ${e.status}): ${String(e.stderr || '').replace(/basic [A-Za-z0-9+/=]+/g, 'basic ***').slice(0, 400)}`); }
};
const id = ['-c', 'user.name=lab-bot', '-c', 'user.email=41898282+github-actions[bot]@users.noreply.github.com'];
git(['init', '-q', '-b', BRANCH]);
git([...id, 'add', '-A']);
git([...id, 'commit', '-q', '-m', `lab: mountains · ${cal.totalContributions} contributions`]);
git(['push', '-q', '--force', `https://github.com/${REPO}.git`, `HEAD:refs/heads/${BRANCH}`], {GIT_CONFIG_COUNT: '1', GIT_CONFIG_KEY_0: 'http.https://github.com/.extraheader', GIT_CONFIG_VALUE_0: auth});
rmSync(dir, {recursive: true, force: true});
console.log(`published ${BRANCH}: ${cal.totalContributions} contributions over ${weeks.length} weeks`);
