// The lab bot. Runs in GitHub Actions (hourly and on "lab:" issues), or locally with GITHUB_TOKEN set.
// 1) reads state.json from the lab-output branch, 2) applies a visitor's action from an issue (switch the lamp / feed the cat),
// 3) fetches a year of contributions, 4) redraws the live SVGs, 5) force-pushes them as a single commit to lab-output,
// 6) thanks the visitor and closes the issue. Issue text is only read from env and never reaches a shell.
import {mkdirSync, writeFileSync, rmSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {THEMES} from './palette.mjs';
import {liveRoom, mountains, bishkek, phaseOf, catMood} from './scenes.mjs';

const REPO = process.env.REPO || 'adilkananarbekov/adilkananarbekov';
const LOGIN = REPO.split('/')[0];
const TOKEN = process.env.GITHUB_TOKEN;
if (!TOKEN) throw new Error('GITHUB_TOKEN is required');
const BRANCH = 'lab-output';
const now = new Date();
const api = async (path, init = {}) => {
  const res = await fetch(`https://api.github.com${path}`, {...init, headers: {authorization: `Bearer ${TOKEN}`, accept: 'application/vnd.github+json', 'user-agent': 'adilkan-lab', 'content-type': 'application/json', ...(init.headers || {})}});
  if (!res.ok) throw new Error(`${init.method || 'GET'} ${path}: ${res.status}`);
  return res.status === 204 ? null : res.json();
};

// 1. State (stored next to the pictures on the output branch).
const EMPTY = {v: 1, lamp: {on: false, by: null, at: null, toggles: 0}, cat: {fed: 0, lastFedAt: null, lastBy: null, feeders: []}, contrib: null};
let state = structuredClone(EMPTY);
try {
  const file = await api(`/repos/${REPO}/contents/state.json?ref=${BRANCH}`);
  state = {...EMPTY, ...JSON.parse(Buffer.from(file.content, 'base64').toString('utf8'))};
} catch (e) { console.log('no previous state, starting fresh'); }

// 2. A visitor's action.
let reply = null;
const issue = process.env.EVENT_NAME === 'issues' ? Number(process.env.ISSUE_NUMBER) : 0;
if (issue) {
  const title = String(process.env.ISSUE_TITLE || '').toLowerCase();
  const user = String(process.env.ISSUE_USER || '').replace(/[^A-Za-z0-9-]/g, '').slice(0, 39) || 'someone';
  if (/lamp|light|свет|ламп/.test(title)) {
    state.lamp = {on: !state.lamp.on, by: user, at: now.toISOString(), toggles: (state.lamp.toggles || 0) + 1};
    reply = `💡 *Click!* The lamp in the live room is now **${state.lamp.on ? 'ON' : 'OFF'}** — switched ${state.lamp.toggles} times so far.\n\nThe picture in the profile README refreshes in a minute or two. Thanks for dropping by, @${user}!`;
  } else if (/feed|cat|fish|кот|корм/.test(title)) {
    state.cat = {fed: (state.cat.fed || 0) + 1, lastFedAt: now.toISOString(), lastBy: user, feeders: [user, ...(state.cat.feeders || []).filter(u => u !== user)].slice(0, 5)};
    reply = `🐟 *Nom nom.* The cat has been fed **${state.cat.fed}** times — and it remembers you, @${user}.\n\nThe live room in the profile README refreshes in a minute or two.`;
  }
}

// 3. Contributions over the last year (kept from the previous run if the API is unavailable).
try {
  const q = `query($login:String!){user(login:$login){contributionsCollection{contributionCalendar{totalContributions weeks{contributionDays{contributionCount date}}}}}}`;
  const res = await fetch('https://api.github.com/graphql', {method: 'POST', headers: {authorization: `Bearer ${TOKEN}`, 'content-type': 'application/json', 'user-agent': 'adilkan-lab'}, body: JSON.stringify({query: q, variables: {login: LOGIN}})});
  const cal = (await res.json()).data.user.contributionsCollection.contributionCalendar;
  state.contrib = {total: cal.totalContributions, weeks: cal.weeks.map(w => ({start: w.contributionDays[0].date, count: w.contributionDays.reduce((s, d) => s + d.contributionCount, 0)}))};
} catch (e) { console.log('contributions unavailable, keeping the previous ones'); }
state.updatedAt = now.toISOString();

// 4. Pictures.
const dir = join(tmpdir(), `lab-${process.pid}`);
rmSync(dir, {recursive: true, force: true}); mkdirSync(dir, {recursive: true});
for (const t of Object.values(THEMES)) {
  writeFileSync(join(dir, `live-${t.name}.svg`), liveRoom(t, state, now, state.contrib?.total ?? null));
  if (state.contrib?.weeks?.length) writeFileSync(join(dir, `mountains-${t.name}.svg`), mountains(t, state.contrib.weeks, state.contrib.total));
}
writeFileSync(join(dir, 'state.json'), JSON.stringify(state, null, 1));
writeFileSync(join(dir, 'README.md'), '# lab-output\n\nGenerated by `lab/run.mjs` (workflow `lab`). Pictures for the profile README and the lab state. Rewritten on every run.\n');

// 5. Publish as a single commit on the output branch (the token goes in an http header, never in a URL or a log line).
const git = (...args) => execFileSync('git', args, {cwd: dir, stdio: ['ignore', 'ignore', 'pipe']});
const auth = `AUTHORIZATION: basic ${Buffer.from(`x-access-token:${TOKEN}`).toString('base64')}`;
git('init', '-q', '-b', BRANCH);
git('-c', 'user.name=lab-bot', '-c', 'user.email=41898282+github-actions[bot]@users.noreply.github.com', 'add', '-A');
const {h, m} = bishkek(now);
git('-c', 'user.name=lab-bot', '-c', 'user.email=41898282+github-actions[bot]@users.noreply.github.com', 'commit', '-q', '-m', `lab: ${issue ? `issue #${issue}` : 'hourly'} · Bishkek ${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')} · ${phaseOf(h)} · lamp ${state.lamp.on ? 'on' : 'off'} · cat ${catMood(state, phaseOf(h), now)}`);
git('-c', `http.https://github.com/.extraheader=${auth}`, 'push', '-q', '--force', `https://github.com/${REPO}.git`, `HEAD:refs/heads/${BRANCH}`);
rmSync(dir, {recursive: true, force: true});
console.log(`published ${BRANCH}: lamp ${state.lamp.on ? 'on' : 'off'}, cat fed ${state.cat.fed}, contributions ${state.contrib?.total ?? '—'}`);

// 6. Answer the visitor.
if (issue) {
  if (reply) await api(`/repos/${REPO}/issues/${issue}/comments`, {method: 'POST', body: JSON.stringify({body: reply})});
  else await api(`/repos/${REPO}/issues/${issue}/comments`, {method: 'POST', body: JSON.stringify({body: 'The lab bot knows two commands: **lab: switch the lamp** and **lab: feed the cat**. Use the buttons in the profile README 🙂'})});
  await api(`/repos/${REPO}/issues/${issue}`, {method: 'PATCH', body: JSON.stringify({state: 'closed', state_reason: reply ? 'completed' : 'not_planned'})});
}
